### PR TITLE
fixed error (test don't merge)

### PR DESCRIPTION
**Pull request by Balackburn**
Hello I tried to update the tweak from the latest version that worked (fec7baaa9d5fd17bd4b75e29238c3ceb412f421a) 
so I got back to it and tried to add localization myself but the problem is I can't test the tweak as I am in vacation and I don't have wifi (only cellular) and can't sideload without WIFI, compiling work but I am not sure it don't break the tweak or make youtube crash etc could you test this code? thx

### CODE REVIEW

**Comment by Balackburn** [comment]
Please try to sideload 
https://github.com/Balackburn/YTLitePlus/releases/tag/v18.27.3-2.3
I compiled it with this edited YTNoCommunityPosts, hope it don't cause problems (I can't test it myself)

**Comment by arichornlover** [comment]
> fixed error (test don't merge)

I can’t even merge because this pull request has conflicts, not because of errors, this only happens to me whenever a large portion of code get changed

> Please try to sideload https://github.com/Balackburn/YTLitePlus/releases/tag/v18.27.3-2.3 I compiled it with this edited YTNoCommunityPosts, hope it don't cause problems (I can't test it myself)

I’m using YouTubeRebornPlus but I guess I can swap it out and try 😉

**Comment by arichornlover** [comment]
`YTSettingsSectionItem *commpost = 
[[%c(YTSettingsSectionItem) alloc] initWithTitle:NSLocalizedString(@"Show Community Posts", @"") titleDescription:NSLocalizedString(@"Enables viewing community posts in app", @"")];` are you sure this will work? I looked in the code and saw the title and description show the original titles? It’s not using the one in the Localizable.strings

**Comment by Balackburn** [comment]
@arichorn I don't know didn't tested the code

**Comment by arichornlover** [comment]
It could be fine I’ll test it whenever I got time later

**Comment by Balackburn** [comment]
@arichorn just tested it don't work

**Comment by arichornlover** [comment]
Oh no. This might not be good.

**Comment by arichornlover** [comment]
Closed Pull Request because I cleaned up the code and inverted the option to “Hide Community Posts”

**Pull request closed without merging**
